### ISSUE TITLE
--quiet fails to work

### ISSUE THREAD

**Issue by devicenull** [madewithlove/license-checker-php#41]
```
$ ./vendor/bin/license-checker check --quiet
PHP Fatal error:  Uncaught TypeError: LicenseChecker\Composer\UsedLicensesRetriever::getComposerLicenses(): Return value must be of type array, null returned in vendor/madewithlove/license-checker/src/Composer/UsedLicensesRetriever.php:35
Stack trace:
#0 vendor/madewithlove/license-checker/src/Composer/UsedLicensesParser.php(21): LicenseChecker\Composer\UsedLicensesRetriever->getComposerLicenses()
#1 vendor/madewithlove/license-checker/src/Commands/CheckLicenses.php(50): LicenseChecker\Composer\UsedLicensesParser->parseLicenses()
#2 vendor/symfony/console/Command/Command.php(291): LicenseChecker\Commands\CheckLicenses->execute()
#3 vendor/symfony/console/Application.php(1014): Symfony\Component\Console\Command\Command->run()
#4 vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#5 vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#6 vendor/madewithlove/license-checker/bin/license-checker(54): Symfony\Component\Console\Application->run()
#7 vendor/bin/license-checker(120): include('...')
#8 {main}
  thrown in vendor/madewithlove/license-checker/src/Composer/UsedLicensesRetriever.php on line 35
$ ./vendor/bin/license-checker check
 --- -------------------------------------------
      dependency
 --- -------------------------------------------
(output truncated)
```

This is with 1.2.0 on php 8.1

**Comment by jdrieghe** [comment]
Thank you for reporting this issue. It should be fixed in the latest release (v1.5)
